about/urls.py
from django.urls import path
from . import views

app_name = 'about'

urlpatterns = [
    path('team/', views.team, name='team'),
    path('members/', views.members, name='members'),
]

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.list, name='list'),
    path('new/', views.create, name='create'),
    path('<int:article_id>/', views.detail, name='detail'),
    path('<int:article_id>/edit/', views.update, name='update'),
    path('<int:article_id>/comments/new/', views.comment_create, name='comment_create'),
    path('<int:article_id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

debugging/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', include('about.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
]

about/models.py
from django.db import models

# Create your models here.

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.conf import settings


class Article(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    title = models.CharField(max_length=120)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

articles/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    title = forms.CharField(label='제목')
    content = forms.CharField(label='내용', widget=forms.Textarea())
    
    class Meta:
        model = Article
        fields = ['title',]


class CommentForm(forms.ModelForm):
    content = forms.CharField(label='댓글', widget=forms.TextInput())
    
    class Meta:
        model = Comment
        fields = ['content',]

about/views.py
from django.shortcuts import render

# Create your views here.
def team(request):
    return render(request, 'about/team.html')
    

def members(request):
    starting_members = ['이상해씨', '파이리', '꼬부기']
    return render(request, 'about/members.html', {'startings': startings})

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

def signup(request):
    if request.method == 'POST':
        signup_form = UserCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            auth_login(request, user)
            return redirect('articles:list')
    else:
        signup_form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'signup_form': signup_form})

def login(request):
    if request.method == 'POST':
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth_login(request, login_form.get_user())
            return redirect(request.GET.get('next') or 'articles:list')
    else:
        login_form = AuthenticationForm()
    return render(request, 'accounts/login.html', {'login_form': login_form})
    
def logout(request):
    auth_logout(request) 
    return redirect('articles:list')

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseForbidden 
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

def list(request):
    articles = Article.objects.all()
    return render(request, 'articles/list.html', {'articles': articles})
    
@login_required
def create(request):
    if request.method == 'POST':
        article_form = ArticleForm(request.POST)
        if article_form.is_valid():
            article = article_form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm()
    return render(request, 'articles/create.html', {'article_form': article_form})

def detail(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comment_form = CommentForm()
    return render(request, 'articles/detail.html', {'article': article, 'comment_form': comment_form})

@login_required
def update(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if article.user != request.user:
        return HttpResponseForbidden("You are not allowed to update this Article")
    if request.method == 'POST':
        article_form = ArticleForm(request.POST, instance=article)
        if article_form.is_valid():
            article_form.save()
            return redirect('articles:detail', article.pk)
    else:
        article_form = ArticleForm(instance=article)
    return render(request, 'articles/update.html', {'article_form': article_form})

@login_required
def delete(request, article_id):
    article = get_object_or_404(Article, pk=article_id)
    if article.user != request.user:
        return HttpResponseForbidden("You are not allowed to delete this Article")
    article.delete()
    return redirect('articles:list')
    
@require_POST
@login_required
def comment_create(request, article_id):
    comment_form = CommentForm(request.POST)
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.user = request.user
        comment.save()
    return redirect('articles:detail', article_id)

@require_POST
@login_required
def comment_delete(request, article_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if comment.user != request.user:
        return HttpResponseForbidden("You are not allowed to delete this Comment")
    comment.delete()
    return redirect('articles:detail', article_id)

about/templates/about/members.html
{% extends 'base.html' %}

{% load static %}

{% block container %}

<h1>멤버 소개</h1>

<ul>
    {% for starting in startings %}
    <li>{{ starting }}</li>
    {% endfor %}
</ul>

{% endblock %}

about/templates/about/team.html
{% extends 'base.html' %}

{% block container %}

<h1>팀 소개</h1>

<ul>
    <li>인터넷을 더 안전하고, 풍요롭고 좋은 사회로 만듭니다.</li>
</ul>

<img src="{% static 'about/cable.jpg' %}"/>

{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block container %}

<h1>로그인</h1>

<form method="post">
    {% csrf_token %}    
    {{ login_form.as_p }}
    <input type="submit" value="로그인"/>
</form>

<a href="{% url 'accounts:signup' %}">회원가입</a>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block container %}

<h1>회원가입</h1>

<form method="post">
    {% csrf_token %}    
    {{ signup_form.as_p }}
    <input type="submit" value="회원가입"/>
</form>

{% endblock %}

articles/templates/articles/create.html
{% extends 'base.html' %}

{% block container %}

<h1>아티클 생성</h1>

<form method="post">
    {% csrf_token %}
    {{ article_form.as_p }}
    <input type="submit" value="확인"/>
</form>

{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block container %}

<h1>{{ article.title }}</h1>

<div>
    <div>작성일: {{ article.created_at }}</div>
    <div>수정일: {{ article.updated_at }}</div>
</div>

<p>
    {{ article.content }}
</p>

<div>
    <a href="{% url 'articles:list' %}">목록</a>    
    {% if article.user == user %}
    <a href="{% url 'articles:update' article.pk %}">수정</a>    
    <a href="/articles/{{ article.pk }}/delete/">삭제</a>    
    {% endif %}
</div>

<hr>

<ul>
    {% for comment in article.comment_set.all %}
    <li>
        {{ comment.content }} - {{ comment.user.username }}, {{ comment.created_at }}
        {% if comment.user == user %}
        <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" style="display: inline-block;">
            {% csrf_token %}
            <input type="submit" value="삭제"/>
        </form>
        {% endif %}
    </li>
    {% endfor %}
</ul>

{% if user.is_authenticated %}
<form action="{% url 'articles:comment_create' article.pk %}" method="post">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit" value="작성"/>
</form>
{% endif %}

{% endblock %}

articles/templates/articles/list.html
{% extends 'base.html' %}

{% block body %}

<h1>아티클 목록</h1>

<div>
    {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}">새 아티클</a>
    {% endif %}
</div>

<ul>
    {% for article in articles %}
    <li>
        <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a> - {{ article.user.username }}
    </li>
    {% endfor %}
</ul>

{% endblock %}

articles/templates/articles/update.html
{% extends 'base.html' %}

{% block container %}

<h1>아티클 수정</h1>

<form method="post">
    {{ article_form.as_p }}
    <input type="submit" value="확인"/>
</form>

{% endblock %}

debugging/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>디버깅</title>
</head>
<body>
    <header>
        <a href="{% url 'articles:list' %}">메인으로</a>
        <a href="{% url 'about:team' %}">팀 소개</a>
        <a href="{% url 'about:members' %}">멤버 소개</a>
    </header>
    <nav>
        {% if user.is_authenticated %}
        <span>{{ user.username }}</span>
        <a href="{% url 'accounts:logout' %}">로그아웃</a>
        {% else %}
        <a href="{% url 'accounts:login' %}">로그인</a> 
        {% endif %}
    </nav>
    <div class="container">
        {% block container %}{% endblock %}
    </div>
</body>
</html>